### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module 

### ISSUE THREAD

**Issue by h-unterp** [SpellcraftAI/openai-streams#28] opened 2023-05-10 00:15 UTC
Trying to use in firebase functions with typescript, getting:

⬢  functions: Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: Error [ERR_REQUIRE_ESM]: require() of ES Module jo_api/functions/node_modules/openai-streams/dist/index.js from jo_api/functions/lib/index.js not supported.
Instead change the require of jo_api/functions/node_modules/openai-streams/dist/index.js in jo_api/functions/lib/index.js to a dynamic import() which is available in all CommonJS modules.

**Comment by ctjlewis** [comment] 2023-05-10 00:17
Duplicate of #24. Error tells you what's wrong, see comment in that thread.

**Closed** 2023-05-10 00:17 UTC

**Comment by ctjlewis** [comment] 2023-05-10 00:19
See also https://medium.com/google-cloud/es-modules-in-cloud-functions-f5be1676c8b5.
